### PR TITLE
changed endpoint /pubkey to /rippleds. flattened the array

### PR DESCRIPTION
**Pull request by hthayko**

### CODE REVIEW

**Comment by wilsonianb** [comment]
Update endpoint here too:
https://github.com/ripple/crawler-api/blob/master/server.js#L22

**Comment by hthayko** [comment]
I did that actually: https://github.com/ripple/crawler-api/pull/1/files

**Comment by wilsonianb** [comment]
woops, you're right

**Comment by hthayko** [comment]
But I forgot to change the readme.md

**Comment by sourencho** [comment]
Can we also have the dictionary version of pubkey on a separate endpoint instead of replacing?

**Comment by wilsonianb** [comment]
I was actually thinking we could replace both /ipps and /pubkey with /rippleds (or /nodes) to be more RESTful

**Comment by sourencho** [comment]
Meaning the user just extracts the data from the one /rippleds endpoint?

**Comment by wilsonianb** [comment]
Yeah, and we could later allow people to drill down with things like GET /rippleds/:public_key/peers or something

**Comment by sourencho** [comment]
sounds good to me

**Comment by hthayko** [comment]
sounds good

**Comment by hthayko** [comment]
any thumbs up ?

**Comment by wilsonianb** [comment]
Could you also remove /ipp, since you can get the same information from /rippleds

**Comment by wilsonianb** [comment]
LGTM :+1:

**Comment by sourencho** [comment]
Hayk and I will update the documentation on this on confluence.

**Comment by wilsonianb** [comment]
cool, thanks

**Pull request merged**
